[package]
name = "luminal_2_eggplant"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[features]
default = []
cuda = ["dep:cudarc", "dep:luminal_cuda"]
metal = ["dep:objc2", "dep:objc2-metal", "dep:objc2-foundation"]

[dependencies]
luminal = { path = "../../" }
luminal_cuda = { path = "../luminal_cuda", optional = true }
cudarc = { version = "0.16.6", features = [
    "f16",
    "cuda-12080",
], optional = true }
#metal-rs = { version = "0.28.0", package = "metal", optional=true }
objc2 = { version = "0.6.2", optional = true }
objc2-metal = { version = "0.3.1", optional = true }
itertools = "0.14.0"
urlencoding = "2.1.3"
webbrowser = "1.0.4"
regex = "1.11.1"
serde_json = "1.0.140"
colored = "3.0.0"
generational-box = "0.6.2"
egg = "0.9.5"
symbolic_expressions = "5.0.3"
rustc-hash = "2.1.1"
rand = "0.9.1"
egraph-serialize = { git = "https://github.com/egraphs-good/egraph-serialize", branch = "main" }
indexmap = "2.9.0"
serde = "1.0.219"
ratatui = "0.29.0"
crossterm = "0.29.0"
libc = "0.2.174"
unicode-width = "0.2"
objc2-foundation = { version = "0.3.1", optional = true }
eframe = "0.28"
egui = "0.28"
anyhow = "1.0.99"

# eggplant related
eggplant = "0.2.6"
derive_more = { version = "2.0.1", features = [
    "deref_mut",
    "deref",
    "into_iterator",
    "debug",
] }
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"
